#You SHOULD NOT edit this until you are told to do so
update-url: "https://mc.fanet.top/e.json"
player-version-higher:
  - " "
  - "&7◈ &4&lFrkの温馨提示"
  - "&7  &c注意到你正在使用「%ver%(%pro%)」, 一个高于该子服服务端的版本"
  - "&7  &c我们十分建议您更换至「%sver%(%spro%)」&c,这将显著提升游戏体验并且减少误封率"
  - " "
player-version-lower:
  - " "
  - "&7◈ &4&lFrkの温馨提示"
  - "&7  &c注意到你正在使用「%ver%(%pro%)」&c, 一个低于该子服服务端的版本"
  - "&7  &c我们十分建议您更换至「%sver%(%spro%)」,这将显著提升游戏体验并且减少误封率"
  - " "