#You SHOULD NOT edit this until you are told to do so
update-url: "https://mc.fanet.top/e.json"
player-version-higher:
  - " "
  - "&7◈ &6LKQ2&7-&bKisa&2tsutai &8»"
  - "  注意到你正在使用「&e%ver%(%pro%)&f」,一个&b高于&f该子服的版本"
  - "  十分建议您更换至「&a%sver%(%spro%)&f」,这将显著提升游戏体验并且减少误封率"
  - " "
player-version-lower:
  - " "
  - "&7◈ &6LKQ2&7-&bKisa&2tsutai &8»"
  - "  &f注意到你正在使用「&e%ver%(%pro%)&f」,一个&c低于&f该子服的版本"
  - "  &f我们十分建议您更换至「&a%sver%(%spro%)&f」,这将显著提升游戏体验并且减少误封率"
  - " "
send-delay: 20 # tick